# Change these first
owner: Botslovers-SL # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
 

status-website:
  cname: uptime.botslovers.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BotsLovers_Uptime
  introMessage: Estado de los servicios de BotsLovers
